---
- hosts: on-prem
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Start Docker service
      service:
        name: Docker
        state: started
        enabled: yes

    - name: Install Git
      apt:
        name: Git
        state: present
        update_cache: yes
    - name: Clone repository
      git:
        repo: 'https://github.com/eeshwarbhati/app-repo.git'
        dest: /app
        version: main